//
// Created by dekke on 05/08/2022.
//

#ifndef MAMAN14_GLOBALS_H
#define MAMAN14_GLOBALS_H

#define MAX_CHARS_IN_LINE 80
#define MAX_LINES_IN_MACRO 10
#define MAX_CHARS_IN_FILE_NAME 50
#define SYMBOL_MAX_CHAR_LENGTH 30
#define FIRST_ADDRESS_IN_OBJ_FILE 100



#endif //MAMAN14_GLOBALS_H
